# The ``example/use_iam_role_in_ci.py`` script setup necessary AWS IAM resources
# to allow the ``cross-aws-account-iam-role-github-oidc``
# GitHub action open id connect IAM role to assume different roles
# on dev, test, prod three AWS accounts. This GitHub action workflow tests
# the GitHub action IAM permission on those three accounts
#
# GitHub Action secrets:
# - AWS_ACCOUNT_ID: devops AWS account id, which is where the ``cross-aws-account-iam-role-github-oidc`` locate at
# - DEV_AWS_ACCOUNT_ID: dev AWS account id
# - TEST_AWS_ACCOUNT_ID: test AWS account id
# - PROD_AWS_ACCOUNT_ID: prod AWS account id
name: test_cross_aws_account_iam_role

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_REGION: "us-east-1"
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_github_open_id_for_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/cross-aws-account-iam-role-github-oidc
          role-session-name: sample_role_session
          aws-region: ${{ env.AWS_REGION }}
      - name: Test Cross Account IAM permission
        env:
          DEV_AWS_ACCOUNT_ID: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
          TEST_AWS_ACCOUNT_ID: ${{ secrets.TEST_AWS_ACCOUNT_ID }}
          PROD_AWS_ACCOUNT_ID: ${{ secrets.PROD_AWS_ACCOUNT_ID }}
        run: |
          python test_cross_aws_account_iam_role.py
